multipath-tools: memory.h is a local header in multipathd/uxclnt.c
If it is removed, the compiler warns: "undefined reference to `FREE'"

Cc: Christophe Varoqui <christophe.varoqui@opensvc.com>
Cc: device-mapper development <dm-devel@redhat.com>
Signed-off-by: Xose Vazquez Perez <xose.vazquez@gmail.com>
(cherry picked from commit 4970e53dbdecef30ba497ef23b8cd651266699ac)