multipath-tools: libmultipath: fix gcc link failure on rcu_register_thread_mb.
Error:
    ../libmultipath/libmultipath.so: undefined reference to
    `rcu_register_thread_mb'
    ../libmultipath/libmultipath.so: undefined reference to
    `rcu_unregister_thread_mb'

Fix:
    Link the libmultipath with -lurcu

Signed-off-by: Gris Ge <fge@redhat.com>
(cherry picked from commit 209bac8ce769648399878d4121c93117215a6fc3)