multipath-tools: replace daddr_t type with long in kpartx/solaris.c
daddr_t is an unknow type for musl libc

musl-gcc output:
solaris.c:14:2: error: unknown type name ‘daddr_t’

Replace it with long.

Compiled tested only, please review.

Cc: Christophe Varoqui <christophe.varoqui@opensvc.com>
Cc: device-mapper development <dm-devel@redhat.com>
Signed-off-by: Xose Vazquez Perez <xose.vazquez@gmail.com>
(cherry picked from commit 3b27391702f4a382494462d43b39ce1aa7db5ff9)