multipath-tools: add limits.h to kpartx/lopart.c
musl libc complains of
lopart.c:76:12: error: ‘PATH_MAX’ undeclared (first use in this function)

Cc: Martin Wilck <mwilck@suse.com>
Cc: Christophe Varoqui <christophe.varoqui@opensvc.com>
Cc: device-mapper development <dm-devel@redhat.com>
Signed-off-by: Xose Vazquez Perez <xose.vazquez@gmail.com>
(cherry picked from commit 847cc43c6c756c0f5b93c098af971d500061ef30)