multipath-tools: add <sys/types.h> to libmultipath/util.h
Require by musl libc:
In file included from pgpolicies.c:9:0:
util.h:11:1: error: unknown type name ‘dev_t’
 dev_t parse_devt(const char *dev_t);

Cc: Christophe Varoqui <christophe.varoqui@opensvc.com>
Cc: device-mapper development <dm-devel@redhat.com>
Signed-off-by: Xose Vazquez Perez <xose.vazquez@gmail.com>
(cherry picked from commit f4f9ed8a1025394947595c645c68107c7d500f4b)